### DISCUSSION TITLE
Announcement: Code quality tools

### DISCUSSION THREAD

**Discussion by aldy505** [TokoBapak/.github#6] [Backend Team Posts]
Karena kalau project open source bisa dapat benefit lebih untuk berbagai tools yang kalau digunakan di private repository harus bayar dan mahal, maka sekalian aja kita manfaatkan benefit ini.

Untuk code quality & code coverage tools, kita pakai Codacy. Sample dashboard yang sudah live (dengan repository yang asli) ada disini: https://app.codacy.com/gh/TokoBapak/mock-payment-provider/dashboard

Nantinya kita bisa cek code quality grade. Contohnya bisa dilihat di URL tadi, bagian kiri atas:
![image](https://user-images.githubusercontent.com/7274326/210158828-1f919133-8d80-4d5b-8262-c394c5ae08d8.png)

Untuk code coverage (kalau belum tahu apa itu code coverage bisa [buka link ini dari Atlassian](https://www.atlassian.com/continuous-delivery/software-testing/code-coverage)), seharusnya simpel, hanya butuh ini di Github Actions workflow:

```yaml
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
```

Tapi ada beberapa skenario dan language yang nggak support submit code coverage dengan cara sesimpel itu, ada artikel tambahannya disini: https://docs.codacy.com/coverage-reporter/uploading-coverage-in-advanced-scenarios/

Apabila ada pertanyaan, boleh ditanyakan di comments daripada kebingungan.
